import { Lexend_Deca, Big_Shoulders_Display } from '@next/font/google';

export const lexendDeca = Lexend_Deca({
    weight: "400",
    subsets: ["latin"],
});

export const bigShouldersDisplay = Big_Shoulders_Display({
    weight: "700",
    subsets: ["latin"],
});

export default function Head() {
    return (
        <>
            <title>Three column layout</title>
            <meta content="width=device-width, initial-scale=1" name="viewport"/>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon-32x32.png"/>
        </>
    )
}
